name: Verify Branch Build
# Run workflow on every push to the master branch
on:
  pull_request:
    branches: [ main ]

jobs:
  verify-build-integrity:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v4
      
    # sets up node
    - name: Setup node 3.x
      uses: actions/setup-node@v4

    # Installs required npm packages
    - name: Installs required npm dependencies
      run: npm install

    # Generate npm build
    - name: Generates npm build
      run: npm run build
